inherit_from:
  - ../contrib/rubocop-legacy.yml

Lint/EmptyClass:
  Exclude:
    - 'test/opentelemetry/sdk/trace/export/batch_span_processor_test.rb'
Metrics/CyclomaticComplexity:
  Max: 9

# Legacy option defaults now appear inside method bodies.
Metrics/PerceivedComplexity:
  Max: 9
